### ISSUE TITLE
The plugin forget the syntax highlight setup

### ISSUE THREAD

**Issue by SayusiAndo** [Downright-Development/Cetriolo#24]
Short description:
after restart the "Text" and the "tag" elements' syntax highlight setups will be overwritten by the default setups. The environment forgets the set up properties.

Netbeans: 7.3.1

Color profile: city lights

To reproducate if centriolo plugin is installed and enabled:
- open netbeans
- set the color profile from default to City lights
- change the Text and Tag color profiles' properties to a color which is different from the default which is the inherited
- save it
- close the Netbeans
- start Netbeans
- check the colors

Result:
- the Tag's foreground and background colors will be inherited
- the Text's foreground and background colors will be inherited

Expected result:
- I want back the set up what I saved

**Comment by Downright-Development** [comment]
Duplicate issue #16
